# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  jwt2webapi:
    image: jwt2webapi
    build:
      context: .
      dockerfile: Jwt2WebApi/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5180:5180
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
